version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: chore
    groups:
      nuget-patch:
        update-types: [patch]
      nuget-updates:
        update-types: [minor, major]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: chore
    groups:
      github-actions-patch:
        update-types: [patch]
      github-actions-updates:
        update-types: [minor, major]
